### ISSUE TITLE
Locality Sensitive Hashing

### ISSUE THREAD

**Issue by bvancea** [bvancea/data-mining-project-2014#1]
Implement LSH to solve assignment 1 of the project.

**Comment by bvancea** [comment]
This currently gets a score of around 0.6 and got us over the easy baseline :)

**Comment by monicadragan** [comment]
Cool !! I created a branch with my implementation - the same thing + it splits the signature matrix in blocks (in mapper) and then identical [hashed] signatures are classified as candidate duplicate videos - (AND between hashes, in reducer). AND is too strict though - finds no duplicates. I should try with OR + do pairwise comparisons of videos from the same bucket to eliminate false positives.

**Comment by bvancea** [comment]
I got better results when hashing the signature matrix directly in the mapper.

Reducer receives all videos hashed in the same band and does pairwise comparisons between them.

Hopefully we get the same results on the test set :+1:

**Comment by bvancea** [comment]
Okay, so there are two ways we can do it:
1. Send video shingles to reducer, reducer checks for duplicates.
2. Send signature matrix column to reducer, reducer checks for duplicates.

Sending the video yields the best score, but that is not really efficient, as the test set might have huge videos.
Sending the signature matrix yields around 0.9/1.0 and there's the advantage that the signature matrix is fixed in size.

**Comment by monicadragan** [comment]
Great - thanks !! 
I wrote a draft report here:
https://www.sharelatex.com/project/5328454ca99749410400220d

They say we should submit this report (one report per team) in the end of the semester.
